### PR TITLE
chore: fix wording in `explain` section

### PR DESCRIPTION
**Pull request by bschaatsbergen**

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Where in the README do you suggest we put the `explain` subcommand @DanielRieske ?

**Comment by DanielRieske** [comment]
I would actually suggest it going first.

**Comment by bschaatsbergen** [comment]
> I would actually suggest it going first.

Fixed 👍🏼

**Review by DanielRieske — APPROVED** [review]
LGTM 🐊

**Pull request merged**
